# Generated by Django 5.1.3 on 2024-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speller_app', '0003_rename_text_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='header',
            field=models.CharField(verbose_name=48),
        ),
    ]
